menus:
    -
        name: 首页
        link: /
    -
        name: 分类
        link: categories/
    -
        name: 标签
        link: tags/
    -
        name: 开源项目
        link: open-source/
    -
        name: 留言板
        link: message/

# Profile
profile:
    location: QingDao, China
    github: litreily
    organization: upc

# Github
github:
  username: litreily
  popular_repos: [hexoBlogProject,jekyllBlog,Student]

# Comments
youyan_username: litreily
duoshuo_username: litreily # 多说配置
#disqus_username: litreily # disqus 配置

# Search
## google | local
search:
    use: local
